"""Render the Markdown writeup to PDF via Typst. No LaTeX required.

WHY A CONVERTER AND NOT A HAND-WRITTEN .typ
Markdown stays canonical. A research paper quotes tens of numbers, every one of
them bound to an artifact through CLAIMS.md, and hand-porting the prose into
Typst means retyping every one — which is precisely the failure the claim ledger
exists to prevent. Generating the .typ keeps a single source of truth for the
prose and lets `just check` keep supervising the numbers in it.

WHY THIS EXISTS AT ALL
The script it replaces detected a `.typ` and compiled it, but for a Markdown
writeup printed "render this elsewhere" and exited 0. Since essentially every
sprint owes a PDF, that left the highest-stakes step unautomated at the worst
possible moment.

SCOPE
This handles the subset of Markdown a paper actually uses: headings, bold/italic,
inline code, pipe tables, images, ordered and unordered lists. It is deliberately
not a general Markdown implementation, and it should stay that way — every
feature added here is a feature that can break the night before a deadline.

Typst is used rather than pandoc because it is pip-installable with wheels for
macOS, Linux and Windows. pandoc's PDF path needs a multi-gigabyte LaTeX install
that cannot be locked in uv.lock, which would break the scaffold's one promise:
`uv sync` and nothing else about your machine matters.

Run with `just paper`, after `uv sync --group paper`.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
WRITEUP = REPO / "writeup"

# Typst markup characters that must be escaped when they appear in plain prose.
# `~` matters more than it looks: in Typst it is a non-breaking space, so an
# unescaped "p ~ M × U × I" silently loses its tilde and nobody notices until
# print. All of these were live bugs.
SPECIALS = "\\#$@<>_*~"

SUPERSCRIPT = str.maketrans("⁰¹²³⁴⁵⁶⁷⁸⁹⁻", "0123456789-")

#: Headings that read better starting a fresh page. Appendices earn a clean
#: break; most sections do not, because forcing one leaves a half-empty page.
PAGE_BREAK_BEFORE = ("Appendix",)

#: Above this many rows a table cannot fit beside its caption on one page, so it
#: is allowed to break rather than be pushed whole onto the next one.
MAX_UNBREAKABLE_ROWS = 14


def preamble(title: str) -> str:
    return f"""// GENERATED by scripts/build_paper.py — do not edit, your changes will be lost.
// Edit the Markdown source instead; this file is rebuilt by `just paper`.
#set document(title: "{title}")
#set page(paper: "a4", margin: (x: 2.2cm, y: 2.2cm), numbering: "1")
#set text(font: ("Libertinus Serif", "New Computer Modern", "Georgia"), size: 10pt)
#set par(justify: true, leading: 0.62em, spacing: 1.0em)
#show heading: set block(above: 1.3em, below: 0.7em)
#show heading.where(level: 1): set text(size: 13pt)
#show heading.where(level: 2): set text(size: 11pt)
#set table(stroke: (x, y) => (
  top: if y <= 1 {{ 0.5pt }} else {{ 0pt }},
  bottom: 0.5pt,
))
#show table.cell.where(y: 0): strong
// Match manual table captions ("*Table 2.* …") so figures and tables read the
// same: bold supplement and number, full stop, then the caption body. A figure
// centres its content, and that centring would otherwise reach the caption too,
// leaving its last line floating in the middle of the page.
#show figure.caption: it => block(width: 100%, align(left, text(size: 9pt)[
  #strong[#it.supplement #context it.counter.display(it.numbering).] #it.body
]))
#show figure: set block(spacing: 1.4em)
#show raw: set text(font: ("DejaVu Sans Mono", "Menlo"), size: 8.5pt)

"""


def protect(text: str, store: list[str]) -> str:
    """Stash an already-converted fragment so later escaping cannot touch it."""
    store.append(text)
    return f"\x00{len(store) - 1}\x00"


def restore(text: str, store: list[str]) -> str:
    return re.sub(r"\x00(\d+)\x00", lambda m: store[int(m.group(1))], text)


def inline(text: str) -> str:
    """Convert one logical block of Markdown inline markup to Typst."""
    kept: list[str] = []

    # Unicode superscripts (10⁻²⁵¹) become real Typst math, which renders in any
    # font. Leaving them as literal glyphs depends on font coverage we cannot
    # rely on, and the failure is silent: a missing glyph, not an error.
    def sup(m):
        return protect(f"$10^({m.group(1).translate(SUPERSCRIPT)})$", kept)

    text = re.sub(r"10([⁰¹²³⁴⁵⁶⁷⁸⁹⁻]+)", sup, text)

    text = re.sub(r"`([^`]+)`", lambda m: protect(f"`{m.group(1)}`", kept), text)
    text = re.sub(r"\*\*([^*]+)\*\*", lambda m: protect(f"*{inline(m.group(1))}*", kept), text)
    ital = r"(?<!\w)\*([^*]+)\*(?!\w)"
    text = re.sub(ital, lambda m: protect(f"_{inline(m.group(1))}_", kept), text)
    text = re.sub(r"(https?://\S+)", lambda m: protect(f'#link("{m.group(1)}")', kept), text)

    for ch in SPECIALS:
        text = text.replace(ch, "\\" + ch)
    return restore(text, kept)


def table(block: list[str]) -> str:
    """A Markdown pipe table becomes a Typst #table with a header row."""
    cells = [[c.strip() for c in r.strip().strip("|").split("|")] for r in block]
    cells = [c for c in cells if not all(set(x) <= set("-: ") for x in c)]
    ncol = max(len(c) for c in cells)
    # Right-aligning numbers reads well; right-aligning sentences does not.
    prose_table = max(len(c) for row in cells for c in row) > 45
    align = "left" if prose_table else "(col, row) => if col == 0 { left } else { right }"
    out = [f"#align(center)[#table(\n  columns: {ncol},\n  align: {align},"]
    for row in cells:
        row = row + [""] * (ncol - len(row))
        out.append("  " + ", ".join(f"[{inline(c)}]" for c in row) + ",")
    out.append(")]")
    return "\n".join(out)


def is_row(s: str) -> bool:
    """A table row starts AND ends with a pipe.

    Requiring both matters. Markdown hard-wraps, and a wrapped prose line
    beginning "|cos| ≈ 0.014 built from…" is not a table row. Checking only the
    leading pipe turned a paragraph into a one-column table.
    """
    return s.startswith("|") and s.endswith("|") and s.count("|") >= 2


def row_count(block: list[str]) -> int:
    def is_rule(r: str) -> bool:
        return all(set(c.strip()) <= set("-: ") for c in r.strip("| \n").split("|"))

    return len([r for r in block if not is_rule(r)])


def keep_together(first: str, second: str, n_rows: int) -> str:
    """Emit two fragments in one block that page breaks will not split."""
    if n_rows > MAX_UNBREAKABLE_ROWS:
        return f"{first}\n\n{second}\n"
    return f"#block(breakable: false)[\n{first}\n\n{second}\n]\n"


def blocks(lines: list[str]):
    """Group hard-wrapped Markdown into logical blocks BEFORE any inline conversion.

    This grouping is the single most important thing in the file. Markdown
    sources hard-wrap at 80 characters, so `**bold**` routinely spans a newline
    and a per-line converter never matches it — the first version of this script
    mangled a contributions list exactly that way, leaking literal asterisks into
    the PDF. Join first, convert second.
    """
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped or stripped == "---":
            i += 1
            continue

        if is_row(stripped):
            buf = []
            while i < len(lines) and is_row(lines[i].strip()):
                buf.append(lines[i])
                i += 1
            yield ("table", buf)
            continue

        if stripped.startswith(("#", "!")):
            yield ("line", stripped)
            i += 1
            continue

        kind = "para"
        if re.match(r"^\d+\.\s", stripped):
            kind = "olist"
        elif stripped.startswith("- "):
            kind = "ulist"

        # A block continues while lines are non-blank and do not begin a new
        # block. Indented lines are continuations of a list item.
        buf = [stripped]
        i += 1
        while i < len(lines):
            nxt = lines[i]
            s = nxt.strip()
            if not s or s == "---" or is_row(s) or s.startswith(("#", "!")):
                break
            if not nxt[:1].isspace() and (re.match(r"^\d+\.\s", s) or s.startswith("- ")):
                break
            buf.append(s)
            i += 1
        yield (kind, " ".join(buf))


def strip_comments(md: str) -> str:
    """Remove HTML comment blocks, including multi-line ones.

    Markdown writeups carry instructions to their author in `<!-- ... -->`, and
    the template's own placeholder starts with one. Without this they render as
    body text — the first build of this file put "The paper SOURCE lives here and
    is committed" on the title page, centred, directly under the title.
    """
    return re.sub(r"<!--.*?-->", "", md, flags=re.DOTALL)


def document_title(md: str) -> str:
    """The level-1 heading. Used for the PDF's document metadata as well as its
    cover line, so the title bar of a PDF reader shows the paper, not a filename."""
    for line in md.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    raise ValueError("no level-1 heading found — the writeup needs a `# Title` line")


def convert(md: str, src: Path) -> str:
    lines = md.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines) and not lines[i].startswith("# "):
        i += 1
    if i >= len(lines):
        raise ValueError("no level-1 heading found — the writeup needs a `# Title` line")
    title = lines[i][2:].strip()
    out.append(f"#align(center)[#text(size: 17pt, weight: 700)[{inline(title)}]]\n")

    # Everything between the title and the first `## ` is the byline block.
    i += 1
    byline = []
    while i < len(lines) and not lines[i].startswith("## "):
        if lines[i].strip() and lines[i].strip() != "---":
            byline.append(inline(lines[i].strip()))
        i += 1
    if byline:
        out.append("#align(center)[" + " \\\n".join(byline) + "]\n")
    out.append("#v(0.6em)\n")

    items = list(blocks(lines[i:]))
    j = 0
    while j < len(items):
        kind, body = items[j]
        nxt = items[j + 1] if j + 1 < len(items) else (None, None)

        # A caption and the thing it captions must not be separated by a page
        # break, and a table must not be split down the middle. Markdown puts
        # table captions BEFORE the table and figure captions AFTER the image, so
        # both pairings are handled here rather than left to Typst's page filler.
        if kind == "para" and re.match(r"\*\*Table \d", body) and nxt[0] == "table":
            out.append(keep_together(inline(body), table(nxt[1]), row_count(nxt[1])))
            j += 2
            continue

        if kind == "line" and (m := re.match(r"!\[[^\]]*\]\(([^)]+)\)", body)):
            target = (src.parent / m.group(1)).resolve()
            try:
                rel = target.relative_to(REPO)
            except ValueError:
                print(f"paper: image outside the repo, skipped: {m.group(1)}", file=sys.stderr)
                j += 1
                continue
            # No `width: 100%`. lab.figstyle authors figures at their final width
            # in inches precisely so 8pt in the figure is 8pt on the page; forcing
            # them to text width upscales a half-width panel and its fonts along
            # with it. `max-width` keeps an oversized image from overflowing
            # without touching one that is already the right size.
            img = f'image("/{rel.as_posix()}")'
            if nxt[0] == "para" and re.match(r"\*\*Figure \d", nxt[1]):
                # A real float. Typst may lift this to the top or bottom of a page
                # and reflow prose around it, which is what stops a tall figure
                # leaving a half-empty page behind it. Typst owns the numbering
                # once it floats, so the Markdown's own "Figure N." prefix is
                # stripped to avoid rendering "Figure 2: Figure 2. …".
                cap = re.sub(r"^\*\*Figure\s+\d+\.\*\*\s*", "", nxt[1])
                out.append(
                    f"#figure(\n  {img},\n  caption: [{inline(cap)}],\n  placement: auto,\n)\n"
                )
                j += 2
                continue
            out.append(f"#block(breakable: false)[#{img}]\n")
            j += 1
            continue

        if kind == "table":
            out.append(table(body) + "\n")
        elif kind == "line":
            heading = body.lstrip("#").strip()
            level = "==" if body.startswith("### ") else "="
            if any(heading.startswith(p) for p in PAGE_BREAK_BEFORE):
                out.append("#pagebreak(weak: true)\n")
            out.append(f"{level} {inline(heading)}\n")
        elif kind == "olist":
            out.append("+ " + inline(re.sub(r"^\d+\.\s+", "", body)) + "\n")
        elif kind == "ulist":
            out.append(f"- {inline(body[2:])}\n")
        else:
            out.append(inline(body) + "\n")
        j += 1

    return "\n".join(out) + "\n"


def find_source() -> Path | None:
    """The Markdown writeup to render.

    Prefers writeup/paper.md; otherwise the single .md in writeup/. Refuses to
    guess between several, because silently rendering the wrong file is worse
    than saying so.
    """
    preferred = WRITEUP / "paper.md"
    if preferred.exists():
        return preferred
    candidates = sorted(WRITEUP.glob("*.md")) if WRITEUP.exists() else []
    if len(candidates) == 1:
        return candidates[0]
    if not candidates:
        return None
    names = ", ".join(p.name for p in candidates)
    print(f"paper: several Markdown sources ({names}).", file=sys.stderr)
    print("       Name the one you want writeup/paper.md, or edit find_source().", file=sys.stderr)
    return None


def main() -> int:
    src = find_source()
    if src is None:
        if not (WRITEUP / "paper.md").exists() and not list(WRITEUP.glob("*.md")):
            print("paper: writeup/ has no Markdown source yet.", file=sys.stderr)
        return 1

    # `.generated.typ` rather than `.typ`, so this never overwrites a Typst file
    # someone wrote by hand, and so .gitignore can exclude the derived one
    # without excluding a hand-authored source.
    typ = src.parent / f"{src.stem}.generated.typ"
    pdf = src.with_suffix(".pdf")

    try:
        md = strip_comments(src.read_text(encoding="utf-8"))
        typst_src = preamble(document_title(md)) + convert(md, src)
    except ValueError as exc:
        print(f"paper: {exc}", file=sys.stderr)
        return 1

    typ.write_text(typst_src, encoding="utf-8")
    print(f"paper: wrote {typ.relative_to(REPO)}")

    try:
        import typst
    except ImportError:
        print("paper: typst is not installed. Run `uv sync --group paper`.", file=sys.stderr)
        return 1

    try:
        typst.compile(str(typ), output=str(pdf), root=str(REPO))
    except typst.TypstError as exc:
        print(f"paper: typst failed\n{exc}", file=sys.stderr)
        return 1
    print(f"paper: wrote {pdf.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
